# Redis

- name: Disable the Redis Module
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable Redis 7
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install the Redis 7
  ansible.builtin.dnf:
    name: redis
    state: latest

- name: Update the Configuration on redis.conf file ( /etc/redis/redis.conf )
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Redis Config - Update Protected Mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: Start Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes