- name: Disable Nginx Module
  ansible.builtin.shell: sudo dnf module disable nginx -y

- name: Enable the Nginx 1.24
  ansible.builtin.shell: sudo dnf module enable nginx:1.24 -y

- name: Install Ngnix
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy Nginx conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup the Application Prerequisities
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Start & Enable Nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
