- name: Copy the Service file
  ansible.builtin.template:
    src: "{{component}}".service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start and Enable the Service
  ansible.builtin.systemd_service:
    name: "{{component}}"
    state: restarted
    enabled: true
    daemon_reload: true